// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:          number;
    paidOrders:              number;
    numberOfClient:          number;
    numberOfProducts:        number;
    productsWithNoInventory: number;
    losInventory:            number;
    notPaidOrders:           number;
}
